#define SIZEX 1300
#define SIZEY 700
extern float GRAVITY;
extern bool Egravity;
extern bool BoxBounce;
extern bool Collision;
extern bool ShowSettings;
extern bool Eviscosity;
extern float viscosity;
extern bool Espawn;
extern float spawnrate;
extern bool CollisionMerge;
extern bool Edecay;
extern bool Edecaylimit;
extern float Bdecay;
extern float decaylimit;
extern bool EMouseattraction;
extern float Mouseattraction;
extern bool MouseSpawnCont;
extern bool MouseSpawn;
extern float MouseSpawnSize;
extern float zoomScale; 
extern float xOffSet;
extern float yOffSet;
extern double old_time;
extern double new_time;
extern bool ShowQuadTree;
extern bool PresCol;
extern bool PresGrav;
